import { User, Package, Locker, Session, PickupLog, AssignmentLog } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@locker.com',
    full_name: 'Admin User',
    phone: '+1234567890',
    role: 'admin',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'courier@locker.com',
    full_name: 'Courier Smith',
    phone: '+1234567891',
    role: 'courier',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    email: 'john@example.com',
    full_name: 'John Doe',
    phone: '+1234567892',
    role: 'user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    email: 'jane@example.com',
    full_name: 'Jane Smith',
    phone: '+1234567893',
    role: 'user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockLockers: Locker[] = [
  {
    id: 'l1',
    locker_number: 'L001',
    size: 'small',
    status: 'occupied',
    location: 'Floor 1 - Section A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l2',
    locker_number: 'L002',
    size: 'small',
    status: 'available',
    location: 'Floor 1 - Section A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l3',
    locker_number: 'L003',
    size: 'medium',
    status: 'occupied',
    location: 'Floor 1 - Section A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l4',
    locker_number: 'L004',
    size: 'medium',
    status: 'available',
    location: 'Floor 1 - Section B',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l5',
    locker_number: 'L005',
    size: 'large',
    status: 'available',
    location: 'Floor 1 - Section B',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l6',
    locker_number: 'L006',
    size: 'small',
    status: 'available',
    location: 'Floor 2 - Section A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l7',
    locker_number: 'L007',
    size: 'medium',
    status: 'maintenance',
    location: 'Floor 2 - Section A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'l8',
    locker_number: 'L008',
    size: 'large',
    status: 'available',
    location: 'Floor 2 - Section B',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockPackages: Package[] = [
  {
    id: 'p1',
    tracking_number: 'TRK001',
    sender_id: '3',
    recipient_id: '4',
    recipient_name: 'Jane Smith',
    recipient_email: 'jane@example.com',
    recipient_phone: '+1234567893',
    locker_id: 'l1',
    status: 'delivered',
    size: 'small',
    description: 'Electronics - Smartphone',
    assigned_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    delivered_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p2',
    tracking_number: 'TRK002',
    recipient_id: '3',
    recipient_name: 'John Doe',
    recipient_email: 'john@example.com',
    recipient_phone: '+1234567892',
    locker_id: 'l3',
    status: 'delivered',
    size: 'medium',
    description: 'Books - Collection',
    assigned_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    delivered_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p3',
    tracking_number: 'TRK003',
    recipient_id: '4',
    recipient_name: 'Jane Smith',
    recipient_email: 'jane@example.com',
    status: 'queued',
    size: 'small',
    description: 'Clothing - Apparel',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p4',
    tracking_number: 'TRK004',
    recipient_id: '3',
    recipient_name: 'John Doe',
    recipient_email: 'john@example.com',
    status: 'assigned',
    size: 'large',
    description: 'Furniture - Chair',
    locker_id: 'l5',
    assigned_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p5',
    tracking_number: 'TRK005',
    recipient_id: '4',
    recipient_name: 'Jane Smith',
    recipient_email: 'jane@example.com',
    status: 'picked_up',
    size: 'medium',
    description: 'Documents - Certificates',
    locker_id: 'l2',
    assigned_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    delivered_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    picked_up_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockSessions: Session[] = [
  {
    id: 's1',
    user_id: '4',
    locker_id: 'l1',
    package_id: 'p1',
    session_type: 'pickup',
    status: 'active',
    facial_recognition_verified: false,
    started_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 's2',
    user_id: '2',
    locker_id: 'l3',
    package_id: 'p2',
    session_type: 'delivery',
    status: 'completed',
    facial_recognition_verified: true,
    started_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's3',
    user_id: '4',
    locker_id: 'l2',
    package_id: 'p5',
    session_type: 'pickup',
    status: 'completed',
    facial_recognition_verified: true,
    started_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockPickupLogs: PickupLog[] = [
  {
    id: 'pl1',
    package_id: 'p5',
    user_id: '4',
    locker_id: 'l2',
    picked_up_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    facial_recognition_verified: true,
    notes: 'Successful pickup with facial recognition',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockAssignmentLogs: AssignmentLog[] = [
  {
    id: 'al1',
    package_id: 'p1',
    locker_id: 'l1',
    assigned_by: '2',
    assigned_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Assigned by courier during delivery',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'al2',
    package_id: 'p2',
    locker_id: 'l3',
    assigned_by: '1',
    assigned_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Manually assigned by admin',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'al3',
    package_id: 'p4',
    locker_id: 'l5',
    assigned_by: '2',
    assigned_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    notes: 'Assigned by courier',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];
